spring:
  application:
    name: movies-api
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/moviesdb

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/auth
  realm: company-services
  resource: movies-api
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true
